//! FIX (Financial Information eXchange) protocol support: framing, a
//! [`StreamParser`] implementation, and raw TCP/TLS transports.
//!
//! This module adds FIX — the institutional trading industry's standard
//! tag=value message protocol — to the protocols already supported by
//! [`crate::protocol`] (WebSocket, HTTP). It is built on the zero-dependency
//! [`fix_codec`] crate, which performs tag=value encoding/decoding with full
//! BodyLength/CheckSum integrity validation.
//!
//! # Architecture
//!
//! Mirroring the existing WebSocket module, framing and parsing are separated:
//!
//! - [`FixFrameStream`] performs **framing**: it reads a byte stream from a
//!   TCP/TLS socket, locates message boundaries using the deterministic
//!   BodyLength (tag 9) framing rules, and yields each complete FIX message as
//!   a `Bytes` frame. The boundary scanner ([`FrameAccumulator`]) is a pure,
//!   deterministic state machine in [`frame`].
//! - [`FixParser`] performs **parsing**: it implements
//!   [`StreamParser<fix_codec::Message>`] by decoding each frame with
//!   [`fix_codec::decode`], validating its declared BodyLength and CheckSum.
//!
//! The wire framing logic deliberately lives in the stream layer (not the
//! parser) because [`StreamParser::parse`] is a stateless associated function —
//! exactly as WebSocket framing lives in the tungstenite stream.
//!
//! # Transports
//!
//! - [`connect_tcp`] — plaintext TCP, for local/trusted links or non-TLS
//!   sessions.
//! - [`connect_tls`] — TLS over TCP via `tokio-rustls` with webpki-roots,
//!   consistent with this workspace's rustls-only policy (no OpenSSL).
//!
//! Both return a [`FixSocket`] split into a receive [`FixStream`] (yielding
//! complete frames) and a send [`FixSink`] (writing encoded frames).
//!
//! # Example
//!
//! ```
//! use barter_integration::protocol::StreamParser;
//! use barter_integration::protocol::fix::FixParser;
//! use fix_codec::{Message, encode};
//!
//! // A FIX message is encoded to its wire form, then parsed back.
//! let mut message = Message::new();
//! message.push(8, "FIX.4.4"); // BeginString
//! message.push(35, "A");      // MsgType = Logon
//! let frame = encode(&message).unwrap();
//!
//! let parsed = FixParser::parse(Ok(frame.into())).unwrap().unwrap();
//! assert_eq!(parsed.msg_type(), Some(&b"A"[..]));
//! ```

pub mod frame;
pub mod stream;
pub mod transport;

pub use frame::{FrameAccumulator, FrameError, MAX_FRAME_LEN};
pub use stream::{FixFrameSink, FixFrameStream, MaybeTlsStream};
pub use transport::{connect_tcp, connect_tls};

use crate::error::SocketError;
use crate::protocol::StreamParser;
use bytes::Bytes;
use serde::{Deserialize, Serialize};
use tokio::io::{ReadHalf, WriteHalf};

/// Convenient type alias for the receive half of a framed FIX socket: a
/// [`FixFrameStream`] over the read half of a plaintext or TLS TCP socket.
pub type FixStream = FixFrameStream<ReadHalf<MaybeTlsStream>>;

/// Convenient type alias for the send half of a framed FIX socket: a
/// [`FixFrameSink`] over the write half of a plaintext or TLS TCP socket.
pub type FixSink = FixFrameSink<WriteHalf<MaybeTlsStream>>;

/// A framed, full-duplex FIX socket.
///
/// Constructed by [`connect_tcp`] or [`connect_tls`]. Receives complete FIX
/// frames via [`stream`](FixSocket::stream) and writes encoded frames via
/// [`sink`](FixSocket::sink).
#[derive(Debug)]
pub struct FixSocket {
    /// Receive half: yields complete FIX frames as [`Bytes`].
    pub stream: FixStream,
    /// Send half: consumes FIX frames as [`Bytes`] and writes them to the wire.
    pub sink: FixSink,
}

/// Transport-level error for a FIX socket: raw I/O or frame boundary failures.
#[derive(Debug, thiserror::Error)]
pub enum FixTransportError {
    /// Underlying socket I/O error.
    #[error("FIX transport IO error: {0}")]
    Io(#[from] std::io::Error),

    /// The byte stream could not be split into a valid FIX frame.
    #[error("FIX frame error: {0}")]
    Framing(#[from] FrameError),

    /// The hostname provided to [`connect_tls`] could not be used as a valid
    /// TLS Server Name Indication (SNI) identifier.
    #[error("invalid TLS server name: {0}")]
    InvalidServerName(String),

    /// The TLS configuration could not be constructed (e.g. no usable protocol
    /// versions for the pinned crypto provider).
    #[error("TLS configuration error: {0}")]
    TlsConfig(#[from] tokio_rustls::rustls::Error),
}

/// All errors generated by the FIX protocol module.
///
/// Combined into one variant on [`SocketError`] so downstream error handling
/// stays uniform across protocols.
#[derive(Debug, thiserror::Error)]
pub enum FixError {
    /// The frame decoded by [`fix_codec::decode`] failed integrity validation
    /// (declared BodyLength/CheckSum did not match the actual bytes).
    #[error("FIX codec error: {0}")]
    Codec(#[from] fix_codec::CodecError),

    /// The transport failed to produce or consume a frame.
    #[error("FIX transport error: {0}")]
    Transport(#[from] FixTransportError),
}

/// Default [`StreamParser`] implementation for a framed FIX socket.
///
/// Each input is a complete FIX frame (as yielded by [`FixFrameStream`]); it is
/// decoded and integrity-validated with [`fix_codec::decode`], producing a
/// [`fix_codec::Message`].
#[derive(
    Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default, Deserialize, Serialize,
)]
pub struct FixParser;

impl StreamParser<fix_codec::Message> for FixParser {
    type Stream = FixStream;
    type Message = Bytes;
    type Error = FixTransportError;

    fn parse(
        input: Result<Bytes, FixTransportError>,
    ) -> Option<Result<fix_codec::Message, SocketError>> {
        let frame = match input {
            Ok(frame) => frame,
            Err(error) => return Some(Err(SocketError::Fix(Box::new(FixError::Transport(error))))),
        };

        Some(
            fix_codec::decode(&frame)
                .map_err(|error| SocketError::Fix(Box::new(FixError::Codec(error)))),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use fix_codec::tags::{BEGIN_STRING, MSG_SEQ_NUM, MSG_TYPE, SENDER_COMP_ID, TARGET_COMP_ID};

    fn logon_frame() -> Vec<u8> {
        let mut message = fix_codec::Message::new();
        message.push(BEGIN_STRING, "FIX.4.4");
        message.push(MSG_TYPE, "A");
        message.push(MSG_SEQ_NUM, "1");
        message.push(SENDER_COMP_ID, "CLIENT1");
        message.push(TARGET_COMP_ID, "EXECUTOR");
        message.push(98, "0");
        message.push(108, "30");
        fix_codec::encode(&message).unwrap()
    }

    #[test]
    fn test_parse_valid_frame() {
        let frame = logon_frame();
        let result = FixParser::parse(Ok(Bytes::from(frame))).unwrap().unwrap();
        assert_eq!(result.msg_type(), Some(&b"A"[..]));
        assert_eq!(result.get(BEGIN_STRING).unwrap().value(), b"FIX.4.4");
    }

    #[test]
    fn test_parse_transport_error() {
        let result = FixParser::parse(Err(FixTransportError::Io(std::io::Error::new(
            std::io::ErrorKind::ConnectionReset,
            "reset",
        ))));
        assert!(matches!(result, Some(Err(SocketError::Fix(_)))));
    }

    #[test]
    fn test_parse_corrupt_frame() {
        // A frame whose CheckSum digit is wrong: integrity validation fails.
        let mut frame = logon_frame();
        let len = frame.len();
        frame[len - 2] = b'0'; // corrupt the last CheckSum digit
        let result = FixParser::parse(Ok(Bytes::from(frame)));
        assert!(matches!(result, Some(Err(SocketError::Fix(_)))));
    }
}
