use super::order::OrderId;
use barter_instrument::{asset::name::AssetNameInternal, instrument::Instrument};
use barter_integration::Side;
use serde::{Deserialize, Serialize};
use smol_str::SmolStr;

/// Normalised Barter private [`Trade`] model.
#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
pub struct Trade {
    pub id: TradeId,
    pub order_id: OrderId,
    pub instrument: Instrument,
    pub side: Side,
    pub price: f64,
    pub quantity: f64,
    pub fees: AssetFees,
}

/// Private [`Trade`] identifier generated by an exchange. Cannot assume this is unique across each
/// [`Exchange`](barter_integration::model::Exchange),
/// [`Market`](barter_integration::model::Market), or
/// [`Instrument`].
#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
pub struct TradeId(pub SmolStr);

impl<S> From<S> for TradeId
where
    S: Into<SmolStr>,
{
    fn from(id: S) -> Self {
        Self(id.into())
    }
}

/// [`Trade`] fees denominated in a [`AssetNameInternal`].
#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
pub struct AssetFees {
    pub asset: AssetNameInternal,
    pub fees: f64,
}

impl AssetFees {
    /// Construct a new [`AssetFees`].
    pub fn new<S>(asset: S, fees: f64) -> Self
    where
        S: Into<AssetNameInternal>,
    {
        Self {
            asset: asset.into(),
            fees,
        }
    }
}
