use crate::{Identifier, instrument::MarketInstrumentData, subscription::Subscription};

use super::Mexc;
use barter_instrument::{
    Keyed, asset::name::AssetNameInternal, instrument::market_data::MarketDataInstrument,
};
use serde::{Deserialize, Serialize};
use smol_str::{SmolStr, StrExt, format_smolstr};

/// Generated Protobuf types used by this connector.
pub mod proto {
    // Generated Protobuf code triggers many Clippy lints which we can safely
    // ignore. The code is auto-generated by `prost` and not meant to be
    // hand-edited, so allow all Clippy warnings within this module.
    #![allow(clippy::all)]
    #![allow(warnings)]
    include!("protobuf_gen/_.rs");
}

/// Wrapper around a market symbol, e.g. `BTCUSDT`.
#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
pub struct MexcMarket(pub SmolStr);

impl<Kind> Identifier<MexcMarket> for Subscription<Mexc, MarketDataInstrument, Kind> {
    fn id(&self) -> MexcMarket {
        mexc_market(&self.instrument.base, &self.instrument.quote)
    }
}

impl<InstrumentKey, Kind> Identifier<MexcMarket>
    for Subscription<Mexc, Keyed<InstrumentKey, MarketDataInstrument>, Kind>
{
    fn id(&self) -> MexcMarket {
        mexc_market(&self.instrument.value.base, &self.instrument.value.quote)
    }
}

impl<InstrumentKey, Kind> Identifier<MexcMarket>
    for Subscription<Mexc, MarketInstrumentData<InstrumentKey>, Kind>
{
    fn id(&self) -> MexcMarket {
        MexcMarket(self.instrument.name_exchange.name().clone())
    }
}

impl AsRef<str> for MexcMarket {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

fn mexc_market(base: &AssetNameInternal, quote: &AssetNameInternal) -> MexcMarket {
    MexcMarket(format_smolstr!("{base}{quote}").to_uppercase_smolstr())
}
