[package]
name = "barter-execution"
version = "0.6.0"
edition = "2024"
authors = ["JustAStream <justastream.code@gmail.com>"]
license = "MIT"
documentation = "https://docs.rs/barter-execution/"
repository = "https://github.com/barter-rs/barter-rs"
readme = "README.md"
description = "Stream private account data from financial venues, and execute (live or mock) orders."
keywords = ["trading", "backtesting", "crypto", "stocks", "investment"]
categories = ["accessibility", "simulation"]


[dependencies]
# Barter Ecosystem
barter-integration = { workspace = true }
barter-instrument = { workspace = true }

# Logging
tracing = { workspace = true }

# Async
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["sync"] }
pin-project = { workspace = true }
futures = { workspace = true }

# Protocol
url = { workspace = true }
tokio-tungstenite = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls", "json"] }

# Data Structures
smol_str = { workspace = true }
fnv = { workspace = true }
rust_decimal = { workspace = true }

# Error
thiserror = { workspace = true }

# SerDe
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
serde_with = { version = "3.12.0", features = ["chrono"] }
serde_repr = { version = "0.1.19" }
serde_urlencoded = { workspace = true }

# Cryptographic Signatures
hmac = { workspace = true }
sha2 = { workspace = true }

# Misc
rand = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
derive_more = { workspace = true, features = [
    "constructor",
    "from",
    "display",
] }

[dev-dependencies]
rust_decimal_macros = { workspace = true }
